name: flutter_application_1
description: "A new Flutter project."
# Следующая строка предотвращает случайную публикацию пакета в
# pub.dev с помощью `flutter pub publish`. Это предпочтительно для частных пакетов.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Ниже указаны версия и номер сборки для вашего приложения.
# Номер версии - это три цифры, разделенные точками, например, 1.2.43
# за ними следует необязательный номер сборки, разделенный знаком +.
# Как версия, так и номер сборки могут быть переопределены в flutter
# создайте, указав --build-name и --build-number соответственно.
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

  # Зависимости укажите другие пакеты, которые необходимы вашему пакету для работы.
  # Чтобы автоматически обновить зависимости вашего пакета до последних версий
  # попробуйте запустить "обновление flutter pub --major-versions". Кроме того,
  # зависимости можно обновить вручную, изменив номера версий, указанные ниже, на
  # последняя версия, доступная на pub.dev. Чтобы узнать, какие зависимости имеют более новые версии
  # запустите `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # Следующий шаг добавит в ваше приложение шрифт Cupertino Icons.
  # Используйте его с классом CupertinoIcons для иконок в стиле iOS.
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Пакет "flutter_lints", представленный ниже, содержит набор рекомендуемых lint для
  # поощрения надлежащей практики программирования. Набор lint, предоставляемый пакетом,
  # активирован в файле "analysis_options.yaml", расположенном в корне вашего веб-сайта.
  # пакет. Смотрите этот файл для получения информации о деактивации определенных правил lint
  # и активации дополнительных правил.
  flutter_lints: ^3.0.0

# Следующий раздел посвящен пакетам Flutter.
flutter:

  # Следующая строка гарантирует, что шрифт Material Icons
  # включен в ваше приложение, чтобы вы могли использовать значки в
  # классе material Icons.
  uses-material-design: true

  # Чтобы добавить ресурсы в свое приложение, добавьте раздел "ресурсы", например, этот:
  # ресурсы:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # Чтобы добавить пользовательские шрифты в свое приложение, добавьте раздел "Шрифты" здесь,
  # в этом разделе "flutter". Каждая запись в этом списке должна содержать ключ
  # "семейство" с названием семейства шрифтов и ключ "шрифты" с
  # списком, содержащим ресурс и другие дескрипторы для шрифта.
  # пример:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  